artifact_location: /home/os_sysadmin/Desktop/workspace/tunm10/mle-1/config/model.yaml/0
creation_time: 1765452832153
experiment_id: '0'
last_update_time: 1765452832153
lifecycle_stage: active
name: Default
