version: '3.8'
services:
  datawarehouse:
    # Set wal_level from replica (default) to logical
    # so that Debezium can capture change
    image: postgres:17
    command: ['postgres', '-c', 'wal_level=logical']
    container_name: cdc-postgresql
    healthcheck:
      test: ['CMD', 'psql', '-U', 'k6', '-c', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=k6
      - POSTGRES_USER=k6
      - POSTGRES_PASSWORD=k6
    volumes: 
      - datawarehouse:/var/lib/postgresql/data

volumes:
  datawarehouse: